import React from 'react';
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import Header from "./components/Header";
import "./globals.css";
import { getCategories } from '@/lib/GoogleSheets/lists';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "YL SPORT",
    description: "Generated by YL SPORT",
};

export default async function RootLayout({children}: Readonly<{children: React.ReactNode}>) {

    const categories = await getCategories();

    return (
        <html lang="es">
            <body className={inter.className}>
                <Header categories={categories} />
                {children}
            </body>
        </html>
    )
}
