import React from 'react';
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import Header from "./components/Header";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "YL SPORT",
    description: "Generated by YL SPORT",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
    return (
        <html lang="es">
            <body className={inter.className}>
                <Header />
                {children}
            </body>
        </html>
    )
}
